#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

# hard stop if theme dev isn't up
if ! lsof -iTCP:9292 -sTCP:LISTEN >/dev/null 2>&1; then
  echo "ERROR: shopify theme dev is not listening on 9292. Start it first."
  exit 1
fi

ITERATIONS="${1:-25}"

for i in $(seq 1 "$ITERATIONS"); do
  echo "=== ITERATION $i/$ITERATIONS ==="

  echo "[1] Run lint + visual tests (expected to fail until improved)"
  set +e
  shopify theme check
  THEME_CHECK=$?
  npm run visual:test
  VISUAL_TEST=$?
  set -e

  if [[ "$THEME_CHECK" -eq 0 && "$VISUAL_TEST" -eq 0 ]]; then
    echo "PASS: theme check + visual tests"
    git status --porcelain
    exit 0
  fi

  echo "[2] Ask Claude to fix what failed (iterate toward oldweb spec)"
  claude -p "
You are working in a Shopify Dawn-based theme.
Goal: converge to a Y2K/eBay-2010 + YouTube-2007 aesthetic WITHOUT adding JS frameworks or bloat.

Hard constraints:
- Do not break OS 2.0 app compatibility (do not remove app block insertion points; preserve theme.liquid script hooks).
- Prefer CSS changes over markup changes.
- Keep performance: avoid heavy JS, avoid large new dependencies.

Workflow you must follow EVERY iteration:
1) Run: shopify theme check
2) Run: npm run visual:test
3) Read failures and screenshot diffs generated by Playwright.
4) Make minimal, surgical edits (primarily CSS) to move UI toward the target.
5) Repeat until both commands pass.

Target aesthetic guidance:
- eBay 2010 / YouTube 2007 cues: boxed layouts, strong borders, table-like grids, compact typography, blue link styling (including visited), subtle gradients allowed, minimal animations.
- Mobile must remain usable and responsive.

Now start by running the two commands and fixing the failures.
" --allowedTools "Read,Edit,Bash" --continue
done
